Repository ThirdLesson/dolfin_back, pull requests merged in 2025-07, with the labels that each got.

#3 [Feat]: 공통 응답 및 예외 처리
  src/main/java/org/scoula/global/exception/CustomException.java
  src/main/java/org/scoula/global/exception/GlobalExceptionHandler.java
  src/main/java/org/scoula/global/exception/errorCode/CommonErrorCode.java
  src/main/java/org/scoula/global/exception/errorCode/ErrorCode.java
  src/main/java/org/scoula/global/response/ApiResponse.java
  src/main/java/org/scoula/global/response/ErrorResponse.java
Labels: enhancement

#6 [feat]: 회계 관련 도메인 추가
  .github/pull_request_template.md
  src/main/java/org/scoula/domain/ledger/entity/AccountType.java
  src/main/java/org/scoula/domain/ledger/entity/LedgerCode.java
  src/main/java/org/scoula/domain/ledger/entity/LedgerEntry.java
  src/main/java/org/scoula/domain/ledger/entity/LedgerType.java
  src/main/java/org/scoula/domain/ledger/entity/LedgerVoucher.java
  src/main/java/org/scoula/domain/ledger/entity/VoucherType.java
Labels: enhancement

#9 [Feat]: 계좌, 지갑, 거래 내역 관련 도메인 추가
  src/main/java/org/scoula/domain/account/entity/Account.java
  src/main/java/org/scoula/domain/ledger/entity/LedgerCode.java
  src/main/java/org/scoula/domain/ledger/entity/LedgerEntry.java
  src/main/java/org/scoula/domain/ledger/entity/LedgerVoucher.java
  src/main/java/org/scoula/domain/ledger/entity/VoucherType.java
  src/main/java/org/scoula/domain/transaction/entity/Transaction.java
  src/main/java/org/scoula/domain/transaction/entity/TransactionStatus.java
  src/main/java/org/scoula/domain/transaction/entity/TransactionType.java
  src/main/java/org/scoula/domain/wallet/entity/Wallet.java
  src/main/java/org/scoula/global/entity/BaseEntity.java
Labels: enhancement

#16 [Fix]: 엔티티 수정
  src/main/java/org/scoula/domain/financialproduct/depositsaving/entity/DepositSaving.java
  src/main/java/org/scoula/domain/financialproduct/financialcompany/entity/FinancialCompany.java
  src/main/java/org/scoula/domain/financialproduct/jeonseloan/entity/JeonseLoan.java
  src/main/java/org/scoula/domain/financialproduct/personalcreditLoan/entity/PersonalCreditLoan.java
  src/main/java/org/scoula/domain/location/entity/Location.java
Labels: enhancement

#20 [Feature]: log transfer change to kafka
  build.gradle
  src/main/java/org/scoula/domain/controller/HealthCheckController.java
  src/main/java/org/scoula/domain/member/service/MemberServiceImpl.java
  src/main/java/org/scoula/global/common/config/RootConfig.java
  src/main/java/org/scoula/global/exception/CustomException.java
  src/main/java/org/scoula/global/exception/GlobalExceptionHandler.java
  src/main/java/org/scoula/global/exception/errorCode/CommonErrorCode.java
  src/main/java/org/scoula/global/kafka/config/KafkaProducerConfig.java
  src/main/java/org/scoula/global/kafka/dto/Common.java
  src/main/java/org/scoula/global/kafka/dto/LogLevel.java
  src/main/java/org/scoula/global/kafka/dto/LogMessage.java
  src/main/java/org/scoula/global/kafka/producer/KafkaProducer.java
  src/main/java/org/scoula/global/kafka/util/LogMessageMapper.java
  src/main/java/org/scoula/global/response/ApiResponse.java
  src/main/java/org/scoula/global/response/SuccessResponse.java
  src/main/resources/application.properties
Labels: enhancement, feature

#34 [Feat]: 환율 api 개발
  src/main/java/org/scoula/domain/exchange/controller/ExchangeRateController.java
  src/main/java/org/scoula/domain/exchange/dto/request/ExchangeBankRequest.java
  src/main/java/org/scoula/domain/exchange/dto/request/ExchangeQuickRequest.java
  src/main/java/org/scoula/domain/exchange/dto/response/BankRateInfo.java
  src/main/java/org/scoula/domain/exchange/dto/response/ExchangeBankResponse.java
  src/main/java/org/scoula/domain/exchange/dto/response/ExchangeQuickResponse.java
  src/main/java/org/scoula/domain/exchange/entity/ExchangeRate.java
  src/main/java/org/scoula/domain/exchange/entity/Type.java
  src/main/java/org/scoula/domain/exchange/exception/ExchangeErrorCode.java
  src/main/java/org/scoula/domain/exchange/mapper/ExchangeRateMapper.java
  src/main/java/org/scoula/domain/exchange/service/ExchangeRateService.java
  src/main/java/org/scoula/domain/exchange/service/ExchangeRateServiceImpl.java
  src/main/java/org/scoula/global/common/config/RootConfig.java
  src/main/resources/org/scoula/domain/exchange/mapper/ExchangeRateMapper.xml
Labels: enhancement, feature

#38 [Feat]: 패스워드 인코딩 추가
  src/main/java/org/scoula/domain/codef/service/CodefApiClient.java
  src/main/java/org/scoula/domain/member/dto/request/JoinRequest.java
  src/main/java/org/scoula/domain/member/service/JoinServiceImpl.java
Labels: enhancement, feature

#40 [Feat]: join member
  src/main/java/org/scoula/domain/codef/service/CodefApiClient.java
  src/main/java/org/scoula/domain/codef/service/CodefAuthService.java
  src/main/java/org/scoula/domain/member/controller/JoinController.java
  src/main/java/org/scoula/domain/member/dto/request/CheckIdRequest.java
  src/main/java/org/scoula/domain/member/dto/request/JoinRequest.java
  src/main/java/org/scoula/domain/member/dto/request/PhoneNumRequest.java
  src/main/java/org/scoula/domain/member/dto/request/PhoneVerificationRequest.java
  src/main/java/org/scoula/domain/member/dto/response/JoinResponse.java
  src/main/java/org/scoula/domain/member/service/JoinService.java
  src/main/java/org/scoula/domain/member/service/JoinServiceImpl.java
  src/main/java/org/scoula/domain/sms/exception/SmsErrorCode.java
  src/main/java/org/scoula/domain/sms/service/SmsService.java
  src/main/java/org/scoula/domain/sms/service/SmsServiceImpl.java
  src/main/java/org/scoula/global/common/config/ServletConfig.java
  src/main/java/org/scoula/global/constants/Currency.java
  src/main/java/org/scoula/global/security/config/SecurityConfig.java
  src/main/resources/application.properties
  src/main/resources/db/migration/V1__Create_init.sql
Labels: enhancement, feature

#43 [Feat]: 외국인 센터/은행 맵 api 개발
  build.gradle
  src/main/java/org/scoula/domain/exchange/controller/ExchangeRateController.java
  src/main/java/org/scoula/domain/exchange/dto/request/ExchangeBankRequest.java
  src/main/java/org/scoula/domain/exchange/dto/request/ExchangeQuickRequest.java
  src/main/java/org/scoula/domain/exchange/dto/response/BankRateInfo.java
  src/main/java/org/scoula/domain/exchange/dto/response/ExchangeBankResponse.java
  src/main/java/org/scoula/domain/exchange/dto/response/ExchangeQuickResponse.java
  src/main/java/org/scoula/domain/exchange/exception/ExchangeErrorCode.java
  src/main/java/org/scoula/domain/exchange/service/ExchangeRateServiceImpl.java
  src/main/java/org/scoula/domain/location/controller/locationController.java
  src/main/java/org/scoula/domain/location/dto/response/CenterItem.java
  src/main/java/org/scoula/domain/location/dto/response/ForeignCenterCsvDto.java
  src/main/java/org/scoula/domain/location/dto/response/LocationResponse.java
  src/main/java/org/scoula/domain/location/entity/Location.java
  src/main/java/org/scoula/domain/location/entity/Point.java
  src/main/java/org/scoula/domain/location/entity/PointTypeHandler.java
  src/main/java/org/scoula/domain/location/exception/LocationErrorCode.java
  src/main/java/org/scoula/domain/location/mapper/LocationMapper.java
  src/main/java/org/scoula/domain/location/service/CsvDataProcessingService.java
  src/main/java/org/scoula/domain/location/service/LocationService.java
  src/main/resources/foreign_center.csv
  src/main/resources/org/scoula/domain/location/mapper/LocationMapper.xml
Labels: enhancement, feature

#52 [HotFix]: kb글자 빼기
  src/main/java/org/scoula/domain/exchange/service/ExchangeRateServiceImpl.java
Labels: feature

#54 [Feat]: 송금 API
  src/main/java/org/scoula/domain/account/exception/AccountErrorCode.java
  src/main/java/org/scoula/domain/account/service/AccountService.java
  src/main/java/org/scoula/domain/account/service/AccountServiceImpl.java
  src/main/java/org/scoula/domain/codef/controller/CodefController.java
  src/main/java/org/scoula/domain/codef/exception/CodefErrorCode.java
  src/main/java/org/scoula/domain/codef/service/CodefAccountService.java
  src/main/java/org/scoula/domain/codef/service/CodefApiClient.java
  src/main/java/org/scoula/domain/ledger/entity/LedgerCode.java
  src/main/java/org/scoula/domain/ledger/entity/LedgerEntry.java
  src/main/java/org/scoula/domain/ledger/entity/LedgerVoucher.java
  src/main/java/org/scoula/domain/ledger/mapper/LedgerCodeMapper.java
  src/main/java/org/scoula/domain/ledger/mapper/LedgerEntryMapper.java
  src/main/java/org/scoula/domain/ledger/mapper/LedgerVoucherMapper.java
  src/main/java/org/scoula/domain/ledger/service/LedgerService.java
  src/main/java/org/scoula/domain/ledger/service/LedgerServiceImpl.java
  src/main/java/org/scoula/domain/member/dto/request/JoinRequest.java
  src/main/java/org/scoula/domain/member/dto/response/JoinResponse.java
  src/main/java/org/scoula/domain/member/dto/response/SignInResponseDto.java
  src/main/java/org/scoula/domain/member/mapper/MemberMapper.java
  src/main/java/org/scoula/domain/member/service/JoinServiceImpl.java
  src/main/java/org/scoula/domain/member/service/MemberService.java
  src/main/java/org/scoula/domain/member/service/MemberServiceImpl.java
  src/main/java/org/scoula/domain/sms/exception/SmsErrorCode.java
  src/main/java/org/scoula/domain/transaction/entity/Transaction.java
  src/main/java/org/scoula/domain/transaction/mapper/TransactionMapper.java
  src/main/java/org/scoula/domain/transaction/service/TransactionService.java
  src/main/java/org/scoula/domain/transaction/service/TransactionServiceImpl.java
  src/main/java/org/scoula/domain/wallet/controller/TransferController.java
  src/main/java/org/scoula/domain/wallet/controller/WalletController.java
  src/main/java/org/scoula/domain/wallet/dto/request/AccountDepositorRequest.java
  src/main/java/org/scoula/domain/wallet/dto/request/TransferToAccountRequest.java
  src/main/java/org/scoula/domain/wallet/dto/request/TransferToWalletRequest.java
  src/main/java/org/scoula/domain/wallet/dto/response/DepositorResponse.java
  src/main/java/org/scoula/domain/wallet/exception/WalletErrorCode.java
  src/main/java/org/scoula/domain/wallet/mapper/WalletMapper.java
  src/main/java/org/scoula/domain/wallet/service/WalletService.java
  src/main/java/org/scoula/domain/wallet/service/WalletServiceImpl.java
  src/main/java/org/scoula/global/security/filter/JwtAuthenticationFilter.java
  src/main/java/org/scoula/global/swagger/config/SwaggerConfig.java
  src/main/resources/db/migration/V6__edit_ledger_voucher.sql
  src/main/resources/org/scoula/domain/ledger/mapper/LedgerCodeMapper.xml
  src/main/resources/org/scoula/domain/ledger/mapper/LedgerEntryMapper.xml
  src/main/resources/org/scoula/domain/ledger/mapper/LedgerVoucherMapper.xml
  src/main/resources/org/scoula/domain/member/mapper/MemberMapper.xml
  src/main/resources/org/scoula/domain/transaction/mapper/TransactionMapper.xml
  src/main/resources/org/scoula/domain/wallet/mapper/WalletMapper.xml
Labels: enhancement, feature

#55 [Feat]: 위치 정보 저장 및 수정
  src/main/java/org/scoula/domain/controller/HealthCheckController.java
  src/main/java/org/scoula/domain/exchange/controller/ExchangeRateController.java
  src/main/java/org/scoula/domain/location/dto/response/ForeignCenterCsvDto.java
  src/main/java/org/scoula/domain/location/dto/response/LocationResponse.java
  src/main/java/org/scoula/domain/location/entity/Location.java
  src/main/java/org/scoula/domain/location/exception/LocationErrorCode.java
  src/main/java/org/scoula/domain/location/mapper/LocationMapper.java
  src/main/java/org/scoula/domain/location/service/CsvDataProcessingService.java
  src/main/java/org/scoula/domain/location/service/LocationService.java
  src/main/resources/db/migration/V7__location_center_edit.sql
  src/main/resources/mybatis-config.xml
  src/main/resources/org/scoula/domain/location/mapper/LocationMapper.xml
Labels: feature

#58 [Feat]: 로그인 성공 반환 형식 변경
  src/main/java/org/scoula/domain/member/dto/response/SignInResponseDto.java
Labels: enhancement

#60 [Feat]: 최근 송금 계좌, 전화번호 내역 조회
  src/main/java/org/scoula/domain/ledger/service/LedgerServiceImpl.java
  src/main/java/org/scoula/domain/member/mapper/MemberMapper.java
  src/main/java/org/scoula/domain/transaction/entity/Transaction.java
  src/main/java/org/scoula/domain/transaction/entity/TransactionType.java
  src/main/java/org/scoula/domain/transaction/mapper/TransactionMapper.java
  src/main/java/org/scoula/domain/transaction/service/TransactionService.java
  src/main/java/org/scoula/domain/transaction/service/TransactionServiceImpl.java
  src/main/java/org/scoula/domain/wallet/controller/TransferController.java
  src/main/java/org/scoula/domain/wallet/dto/request/TransferToAccountRequest.java
  src/main/java/org/scoula/domain/wallet/dto/response/RecentAccountReceiversResponse.java
  src/main/java/org/scoula/domain/wallet/dto/response/RecentWalletReceiversResponse.java
  src/main/java/org/scoula/domain/wallet/service/WalletService.java
  src/main/java/org/scoula/domain/wallet/service/WalletServiceImpl.java
  src/main/resources/db/migration/V8__edit_transaction.sql
  src/main/resources/org/scoula/domain/ledger/mapper/LedgerVoucherMapper.xml
  src/main/resources/org/scoula/domain/member/mapper/MemberMapper.xml
  src/main/resources/org/scoula/domain/transaction/mapper/TransactionMapper.xml
Labels: enhancement, feature

#62 [HotFix]: ExchangeRateController swagger 수정
  src/main/java/org/scoula/domain/exchange/controller/ExchangeRateController.java
Labels: hot-fix

#63 [Feat]: 거래 내역 리스트 조회 API
  src/main/java/org/scoula/domain/transaction/controller/TransactionController.java
  src/main/java/org/scoula/domain/transaction/dto/response/TransactionHistoryResponse.java
  src/main/java/org/scoula/domain/transaction/dto/response/TransactionResponse.java
  src/main/java/org/scoula/domain/transaction/entity/TransactionType.java
  src/main/java/org/scoula/domain/transaction/mapper/TransactionMapper.java
  src/main/java/org/scoula/domain/transaction/service/TransactionService.java
  src/main/java/org/scoula/domain/transaction/service/TransactionServiceImpl.java
  src/main/java/org/scoula/global/common/config/ServletConfig.java
  src/main/java/org/scoula/global/constants/Period.java
  src/main/java/org/scoula/global/constants/SortDirection.java
  src/main/resources/db/migration/V9__edit_transaction.sql
  src/main/resources/org/scoula/domain/transaction/mapper/TransactionMapper.xml
Labels: enhancement, feature

#65 [Feature]: 로그인 반환 형식 변경
  src/main/java/org/scoula/domain/account/entity/BankType.java
  src/main/java/org/scoula/domain/codef/exception/CodefErrorCode.java
  src/main/java/org/scoula/domain/codef/service/CodefAccountService.java
  src/main/java/org/scoula/domain/member/dto/response/SignInResponseDto.java
  src/main/resources/db/migration/V10__edit_bank_type.sql
Labels: enhancement
