Repository ThirdLesson/dolfin_back, pull requests merged in 2025-08, with the labels that each got.

#71 [Fix]: 전화번호 입력 및 반환 포맷 변경
  src/main/java/org/scoula/domain/member/dto/request/JoinRequest.java
  src/main/java/org/scoula/domain/member/service/JoinServiceImpl.java
  src/main/java/org/scoula/domain/sms/service/SmsServiceImpl.java
  src/main/java/org/scoula/domain/wallet/service/WalletServiceImpl.java
Labels: hot-fix

#75 [Fix]: 거래내역 조회시 반환 타입 변경
  src/main/java/org/scoula/domain/transaction/dto/response/TransactionResponse.java
  src/main/java/org/scoula/domain/transaction/entity/TransactionType.java
  src/main/java/org/scoula/domain/transaction/service/TransactionServiceImpl.java
  src/main/resources/db/migration/V12__edit_transaction_type.sql
Labels: enhancement, hot-fix

#76 [Feat]: 해외 단체 정기 송금 로직 구현
  build.gradle
  src/main/java/org/scoula/domain/codef/service/CodefAccountService.java
  src/main/java/org/scoula/domain/member/dto/MemberDTO.java
  src/main/java/org/scoula/domain/member/entity/Member.java
  src/main/java/org/scoula/domain/member/mapper/MemberMapper.java
  src/main/java/org/scoula/domain/remittanceGroup/entity/RemittanceGroup.java
  src/main/java/org/scoula/domain/remittancegroup/controller/RemittanceGroupController.java
  src/main/java/org/scoula/domain/remittancegroup/dto/request/JoinRemittanceGroupRequest.java
  src/main/java/org/scoula/domain/remittancegroup/dto/request/RemittanceGroupMemberCountRequest.java
  src/main/java/org/scoula/domain/remittancegroup/dto/response/RemittanceGroupCommissionResponse.java
  src/main/java/org/scoula/domain/remittancegroup/dto/response/RemittanceGroupMemberCountResponse.java
  src/main/java/org/scoula/domain/remittancegroup/entity/BenefitStatus.java
  src/main/java/org/scoula/domain/remittancegroup/entity/RemittanceGroup.java
  src/main/java/org/scoula/domain/remittancegroup/exception/RemittanceGroupErrorCode.java
  src/main/java/org/scoula/domain/remittancegroup/mapper/RemittanceGroupMapper.java
  src/main/java/org/scoula/domain/remittancegroup/service/RemittanceService.java
  src/main/java/org/scoula/domain/remittancegroup/service/RemittanceServiceImpl.java
  src/main/java/org/scoula/domain/remmitanceinformation/entity/IntermediaryBankCommission.java
  src/main/java/org/scoula/domain/remmitanceinformation/entity/RemittanceInformation.java
  src/main/java/org/scoula/domain/remmitanceinformation/entity/Status.java
  src/main/java/org/scoula/domain/remmitanceinformation/mapper/RemittanceInformationMapper.java
  src/main/java/org/scoula/global/common/config/RootConfig.java
  src/main/java/org/scoula/global/firebase/config/FirebaseConfig.java
  src/main/java/org/scoula/global/firebase/event/RemittanceGroupCompletedEvent.java
  src/main/java/org/scoula/global/firebase/listener/RemittanceGroupEventListener.java
  src/main/java/org/scoula/global/firebase/util/FirebaseUtil.java
  src/main/resources/application.properties
  src/main/resources/db/migration/V13__edit_remittance.sql
  src/main/resources/org/scoula/domain/member/mapper/MemberMapper.xml
Labels: enhancement, feature

#78 [Fix]: 송금 시 상대방 이름 저장하도록 변경
  src/main/java/org/scoula/domain/remittancegroup/controller/RemittanceGroupController.java
  src/main/java/org/scoula/domain/transaction/service/TransactionService.java
  src/main/java/org/scoula/domain/transaction/service/TransactionServiceImpl.java
  src/main/java/org/scoula/domain/wallet/controller/TransferController.java
  src/main/java/org/scoula/domain/wallet/service/WalletService.java
  src/main/java/org/scoula/domain/wallet/service/WalletServiceImpl.java
Labels: bug, hot-fix

#80 [Fix]: 거래내역 withdraw로 조회 시 모든 출금내역이 보이도록 수정
  src/main/java/org/scoula/domain/account/entity/BankType.java
  src/main/java/org/scoula/domain/transaction/mapper/TransactionMapper.java
  src/main/java/org/scoula/domain/transaction/service/TransactionServiceImpl.java
  src/main/resources/db/migration/V14__edit_bank_type.sql
  src/main/resources/org/scoula/domain/transaction/mapper/TransactionMapper.xml
Labels: bug, hot-fix

#86 [Feat]: exchange에 실시간 환율 api
  src/main/java/org/scoula/domain/exchange/controller/ExchangeRateController.java
  src/main/java/org/scoula/domain/exchange/dto/response/ExchangeLiveResponse.java
  src/main/java/org/scoula/domain/exchange/service/ExchangeRateQuickService.java
  src/main/java/org/scoula/domain/exchange/service/ExchangeRateQuickServiceImpl.java
Labels: enhancement, feature

#89 [HotFix]: cors 추가
  src/main/java/org/scoula/global/security/config/SecurityConfig.java
Labels: feature

#99 [Feat]: 차대변 정합성 검증을 위한 배치 기능 작성
  src/main/java/org/scoula/domain/ledger/batch/config/LedgerBatchConfig.java
  src/main/java/org/scoula/domain/ledger/batch/dto/LedgerVoucherWithEntryDTO.java
  src/main/java/org/scoula/domain/ledger/batch/reader/LedgerIdRangePartitioner.java
  src/main/java/org/scoula/domain/ledger/batch/reader/LedgerReader.java
  src/main/java/org/scoula/domain/ledger/batch/scheduler/LedgerValidateBatchScheduler.java
  src/main/java/org/scoula/domain/ledger/batch/writer/LedgerWriter.java
  src/main/java/org/scoula/domain/ledger/exception/LedgerErrorCode.java
  src/main/java/org/scoula/domain/ledger/mapper/LedgerVoucherMapper.java
  src/main/java/org/scoula/domain/ledger/service/LedgerService.java
  src/main/java/org/scoula/domain/ledger/service/LedgerServiceImpl.java
  src/main/java/org/scoula/domain/transaction/mapper/TransactionMapper.java
  src/main/java/org/scoula/domain/transaction/service/TransactionService.java
  src/main/java/org/scoula/domain/transaction/service/TransactionServiceImpl.java
  src/main/java/org/scoula/global/batch/config/BatchConfig.java
  src/main/java/org/scoula/global/common/config/RootConfig.java
Labels: enhancement, feature

#102 [Feat]: 개인 신용 대출 api 개발
  src/main/java/org/scoula/domain/financialproduct/personalcreditloan/controller/PersonalCreditLoanController.java
  src/main/java/org/scoula/domain/financialproduct/personalcreditloan/controller/PersonalLoanController.java
  src/main/java/org/scoula/domain/financialproduct/personalcreditloan/dto/PersonalCreditLoanDTO.java
  src/main/java/org/scoula/domain/financialproduct/personalcreditloan/dto/request/PersonalLoanSearchRequest.java
  src/main/java/org/scoula/domain/financialproduct/personalcreditloan/dto/response/PersonalLoanEachResponse.java
  src/main/java/org/scoula/domain/financialproduct/personalcreditloan/dto/response/PersonalLoanListResponse.java
  src/main/java/org/scoula/domain/financialproduct/personalcreditloan/dto/response/PersonalSearchResponse.java
  src/main/java/org/scoula/domain/financialproduct/personalcreditloan/entity/PersonalCreditLoan.java
  src/main/java/org/scoula/domain/financialproduct/personalcreditloan/excpetion/PersonalLoanErrorCode.java
  src/main/java/org/scoula/domain/financialproduct/personalcreditloan/mapper/PersonalCreditLoanMapper.java
  src/main/java/org/scoula/domain/financialproduct/personalcreditloan/service/PersonalCreditLoanService.java
  src/main/java/org/scoula/domain/financialproduct/personalcreditloan/service/PersonalCreditLoanServiceImpl.java
  src/main/java/org/scoula/domain/financialproduct/personalcreditloan/service/PersonalLoanService.java
  src/main/resources/db/migration/V21__edit_personal_loan.sql
  src/main/resources/org/scoula/domain/financialproduct/personalcreditloan/mapper/PersonalCreditLoanMapper.xml
Labels: enhancement, feature

#109 [fix] 전세대출 빌드 실패
  src/main/java/org/scoula/domain/financialproduct/constants/JeonseLoanRateType.java
  src/main/java/org/scoula/domain/financialproduct/helper/JeonseLoanApiHelper.java
  src/main/java/org/scoula/domain/financialproduct/jeonseloan/service/JeonseLoanServiceImpl.java
Labels: bug, fix

#113 [Fix] 전세자금대출 db수정
  .idea/dataSources.xml
  .idea/sqldialects.xml
  src/main/java/org/scoula/domain/financialproduct/constants/JeonseLoanRateType.java
  src/main/java/org/scoula/domain/financialproduct/jeonseloan/dto/JeonseLoanDTO.java
  src/main/java/org/scoula/domain/financialproduct/jeonseloan/entity/JeonseLoan.java
  src/main/java/org/scoula/domain/financialproduct/jeonseloan/service/JeonseLoanServiceImpl.java
  src/main/java/org/scoula/domain/financialproduct/personalcreditloan/dto/request/PersonalLoanSearchRequest.java
  src/main/resources/org/scoula/domain/financialproduct/jeonseloan/mapper/JeonseLoanMapper.xml
Labels: fix

#114 [Fix] 전세대출필터링 조건 수정
  src/main/resources/org/scoula/domain/financialproduct/jeonseloan/mapper/JeonseLoanMapper.xml
Labels: fix

#115 [Feat]: 단체 송금 최소, 여부 가입 api 개발
  src/main/java/org/scoula/domain/remittancegroup/controller/RemittanceGroupController.java
  src/main/java/org/scoula/domain/remittancegroup/dto/response/RemittanceGroupCheckResponse.java
  src/main/java/org/scoula/domain/remittancegroup/exception/RemittanceGroupErrorCode.java
  src/main/java/org/scoula/domain/remittancegroup/mapper/RemittanceGroupMapper.java
  src/main/java/org/scoula/domain/remittancegroup/service/RemittanceService.java
  src/main/java/org/scoula/domain/remittancegroup/service/RemittanceServiceImpl.java
Labels: enhancement, feature

#119 Fix RemittanceGroupCheckResponse 수정
  src/main/java/org/scoula/domain/remittancegroup/dto/response/RemittanceGroupCheckResponse.java
  src/main/java/org/scoula/domain/remittancegroup/service/RemittanceServiceImpl.java
Labels: fix

#121 [Fix] 실시간 환율 정보 api 수정
  src/main/java/org/scoula/domain/exchange/controller/ExchangeRateController.java
  src/main/java/org/scoula/domain/exchange/dto/response/ExchangeConcurrencyList.java
  src/main/java/org/scoula/domain/exchange/dto/response/ExchangeLiveResponse.java
  src/main/java/org/scoula/domain/exchange/mapper/ExchangeRateMapper.java
  src/main/java/org/scoula/domain/exchange/service/ExchangeRateQuickService.java
  src/main/java/org/scoula/domain/exchange/service/ExchangeRateQuickServiceImpl.java
  src/main/resources/org/scoula/domain/exchange/mapper/ExchangeRateMapper.xml
Labels: bug, enhancement

#131 [Fix]: 거래내역 조회 시 기간 별 필터링이 에러 해결
  src/main/java/org/scoula/global/constants/Period.java
Labels: bug, fix

#140 [refactor] 코드 주석제거
  src/main/java/org/scoula/domain/location/entity/Location.java
  src/main/java/org/scoula/domain/location/entity/Point.java
  src/main/java/org/scoula/domain/location/service/CsvDataProcessingService.java
  src/main/java/org/scoula/domain/location/service/LocationService.java
  src/main/java/org/scoula/domain/member/dto/MemberDTO.java
  src/main/java/org/scoula/domain/member/entity/Member.java
  src/main/java/org/scoula/domain/member/exception/MemberErrorCode.java
  src/main/java/org/scoula/domain/member/mapper/MemberMapper.java
  src/main/java/org/scoula/domain/member/service/JoinServiceImpl.java
  src/main/java/org/scoula/domain/member/service/MemberAuthServiceImpl.java
  src/main/java/org/scoula/domain/member/service/MemberService.java
  src/main/java/org/scoula/domain/member/service/MemberServiceImpl.java
  src/main/java/org/scoula/domain/remittancegroup/batch/dto/MemberWithInformationDto.java
  src/main/java/org/scoula/domain/remittancegroup/batch/scheduler/RemittanceGroupScheduler.java
  src/main/java/org/scoula/domain/remittancegroup/batch/writer/RemittanceGroupAutoJoinWriter.java
  src/main/java/org/scoula/domain/remittancegroup/entity/RemittanceGroup.java
  src/main/java/org/scoula/domain/remittancegroup/service/RemittanceServiceImpl.java
  src/main/java/org/scoula/domain/remmitanceinformation/entity/RemittanceInformation.java
  src/main/java/org/scoula/domain/sms/service/SmsServiceImpl.java
  src/main/java/org/scoula/domain/transaction/entity/Transaction.java
  src/main/java/org/scoula/domain/transaction/entity/TransactionStatus.java
  src/main/java/org/scoula/domain/transaction/entity/TransactionType.java
  src/main/java/org/scoula/domain/wallet/entity/Wallet.java
  src/main/java/org/scoula/domain/wallet/service/WalletServiceImpl.java
  src/main/java/org/scoula/global/common/config/ContextFinalizer.java
  src/main/java/org/scoula/global/common/config/RootConfig.java
  src/main/java/org/scoula/global/common/config/ServletConfig.java
  src/main/java/org/scoula/global/common/config/WebConfig.java
  src/main/java/org/scoula/global/exception/GlobalExceptionHandler.java
  src/main/java/org/scoula/global/exception/errorCode/CommonErrorCode.java
  src/main/java/org/scoula/global/firebase/listener/RemittanceGroupEventListener.java
  src/main/java/org/scoula/global/kafka/util/LogMessageMapper.java
  src/main/java/org/scoula/global/redis/config/RedisConfig.java
  src/main/java/org/scoula/global/redis/config/RedisShedLockConfig.java
  src/main/java/org/scoula/global/redis/util/RedisUtil.java
  src/main/java/org/scoula/global/security/config/SecurityConfig.java
  src/main/java/org/scoula/global/security/exception/CustomAuthenticationEntryPoint.java
  src/main/java/org/scoula/global/security/filter/JwtAuthenticationFilter.java
  src/main/java/org/scoula/global/security/util/JwtTokenProvider.java
  src/main/java/org/scoula/global/swagger/config/SwaggerConfig.java
  src/main/resources/org/scoula/domain/exchange/mapper/ExchangePolicyMapper.xml
  src/main/resources/org/scoula/domain/exchange/mapper/ExchangeRateMapper.xml
  src/main/resources/org/scoula/domain/financialproduct/depositsaving/mapper/DepositMapper.xml
  src/main/resources/org/scoula/domain/financialproduct/depositsaving/mapper/SavingMapper.xml
  src/main/resources/org/scoula/domain/financialproduct/financialcompany/mapper/FinancialCompanyMapper.xml
  src/main/resources/org/scoula/domain/financialproduct/jeonseloan/mapper/JeonseLoanMapper.xml
  src/main/resources/org/scoula/domain/financialproduct/personalcreditloan/mapper/PersonalCreditLoanMapper.xml
  src/main/resources/org/scoula/domain/location/mapper/LocationMapper.xml
  src/main/resources/org/scoula/domain/member/mapper/MemberMapper.xml
  src/main/resources/org/scoula/domain/transaction/mapper/TransactionMapper.xml
Labels: fix, refactor

#142 [Fix]: 리프레시 토큰 만료 시 에러 캐치 실패 오류 해결
  src/main/java/org/scoula/domain/member/service/MemberAuthServiceImpl.java
Labels: bug, fix

#148 [Docs] edit readme
  README.md
Labels: documentation
